service: serverless-site

plugins:
  - serverless-pseudo-parameters

custom:
  bucketName: serverless-site-notes-app-uploads-${self:provider.stage}-#{AWS::Region}
  tableName: serverless-site-notes-${self:provider.stage}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  versionFunctions: false

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: 
              - "*"
              AllowedMethods:
              - GET
              - PUT
              - POST
              - HEAD
              - DELETE
              AllowedOrigins: 
              - "*"
              MaxAge: 3000

    DynamoDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: noteId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: noteId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
